services:
  email-tracker.catalin-trandafir.com:
    build:
      context: "./email-tracker"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=DEV
      - PORT=3000
    env_file:
      - ./email-tracker/.env
    networks:
      - email-tracker-network
    volumes:
      - ./email-tracker/src:/usr/src/app

  email-tracker-redis:
    build:
      context: "./redis"
    restart: always
    ports:
      - 6379:6379
    networks:
      - email-tracker-network
    volumes:
      - redis-data:/data
networks:
  email-tracker-network:
volumes:
  redis-data:
