services:
  email-tracker.catalin-trandafir.com:
    build:
      context: "./email-tracker"
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    env_file:
      - ./email-tracker/docker.env
      - ./email-tracker/secret.env
    networks:
      - email-tracker-network
    volumes:
      - ./email-tracker/src:/usr/src/app

  email-tracker-redis:
    build:
      context: "./redis"
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 6379:6379
    networks:
      - email-tracker-network
    volumes:
      - redis-data:/data
    mem_limit: 150m
networks:
  email-tracker-network:
volumes:
  redis-data:
